-- 需求优先级(P0/P1/P2/P3)与需求类型(FEATURE/ENHANCEMENT/TECH_DEBT/BUGFIX),存量行取默认值。
ALTER TABLE ms_requirement ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'P2';
ALTER TABLE ms_requirement ADD COLUMN IF NOT EXISTS req_type TEXT NOT NULL DEFAULT 'FEATURE';
