[package]
name = "bug"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true, optional = true }
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "json"], optional = true }
axum = { workspace = true, optional = true }
utoipa = { workspace = true, optional = true }
webauth = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[features]
pg = ["dep:sqlx", "dep:serde_json"]
http = ["dep:axum", "dep:serde", "dep:webauth", "webauth/http", "dep:utoipa"]

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = { workspace = true, features = ["util"] }
serde_json = { workspace = true }
migrate = { workspace = true }
kernel = { workspace = true }
webauth = { workspace = true, features = ["http", "test-util"] }

[lints]
workspace = true
