[package]
name = "bug"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait = "0.1"
thiserror = "2"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "postgres"], optional = true }
axum = { version = "0.8", optional = true }
utoipa = { version = "5", optional = true }
webauth = { path = "../webauth", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[features]
pg = ["dep:sqlx"]
http = ["dep:axum", "dep:serde", "dep:webauth", "webauth/http", "dep:utoipa"]

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5", features = ["util"] }
serde_json = "1"
migrate = { path = "../migrate" }
kernel = { path = "../kernel" }
webauth = { path = "../webauth", features = ["http", "test-util"] }

[lints]
workspace = true
